In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv("D:\\Datasets\\netflix_titles.csv")

In [3]:
movies.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."

In [4]:
movies.shape

(8807, 12)

In [5]:
movies.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [6]:
movies.dropna(inplace=True)

In [7]:
movies.isna().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [8]:
movies.duplicated().sum()

np.int64(0)

In [9]:
movies.describe()

       release_year
count   5332.000000
mean    2012.742123
std        9.625831
min     1942.000000
25%     2011.000000
50%     2016.000000
75%     2018.000000
max     2021.000000

In [10]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5332 entries, 7 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       5332 non-null   object
 1   type          5332 non-null   object
 2   title         5332 non-null   object
 3   director      5332 non-null   object
 4   cast          5332 non-null   object
 5   country       5332 non-null   object
 6   date_added    5332 non-null   object
 7   release_year  5332 non-null   int64
 8   rating        5332 non-null   object
 9   duration      5332 non-null   object
 10  listed_in     5332 non-null   object
 11  description   5332 non-null   object
dtypes: int64(1), object(11)
memory usage: 541.5+ KB

In [11]:
movies['date_added'] = pd.to_datetime(movies['date_added'],format='mixed')

In [12]:
movies.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",2021-09-24,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,2021-09-24,2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,2021-09-24,2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic",2021-09-23,2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,2021-09-21,1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...

In [13]:
movies ['tags'] = movies['type'] + "," + movies['description'] + "," + movies['director'] + "," + movies['cast'] + "," +  movies['listed_in']

In [14]:
movies.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,tags
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",2021-09-24,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s...","Movie,On a photo shoot in Ghana, an American m..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,2021-09-24,2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...,"TV Show,A talented batch of amateur bakers fac..."

In [15]:
new_df = movies[['show_id','title','tags']]

In [16]:
new_df

,show_id,title,tags
7,s8,Sankofa,"Movie,On a photo shoot in Ghana, an American m..."
8,s9,The Great British Baking Show,"TV Show,A talented batch of amateur bakers fac..."
9,s10,The Starling,"Movie,A woman adjusting to life after a loss c..."
12,s13,Je Suis Karl,"Movie,After most of her family is murdered in ..."
24,s25,Jeans,"Movie,When the father of the man she loves ins..."
...,...,...,...
8801,s8802,Zinzana,"Movie,Recovering alcoholic Talal wakes up insi..."
8802,s8803,Zodiac,"Movie,A political cartoonist, a crime reporter..."
8804,s8805,Zombieland,"Movie,Looking to survive in a world taken over..."
8805,s8806,Zoom,"Movie,Dragged from civilian life, a former sup..."
8806,s8807,Zubaan,"Movie,A scrappy but poor boy worms his way int..."

In [29]:
import nltk

In [30]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [31]:
def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [33]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\ANUSHKA\AppData\Local\Temp\ipykernel_15536\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [34]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\ANUSHKA\AppData\Local\Temp\ipykernel_15536\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [35]:
new_df['tags']

7       movie,on a photo shoot in ghana, an american m...
8       tv show,a talent batch of amateur baker face o...
9       movie,a woman adjust to life after a loss cont...
12      movie,aft most of her famili is murder in a te...
24      movie,when the father of the man she love insi...
                              ...
8801    movie,recov alcohol talal wake up insid a smal...
8802    movie,a polit cartoonist, a crime report and a...
8804    movie,look to surviv in a world taken over by ...
8805    movie,drag from civilian life, a former superh...
8806    movie,a scrappi but poor boy worm hi way into ...
Name: tags, Length: 5332, dtype: object

In [42]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=10000, stop_words= 'english')

In [43]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [44]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [45]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'şafak', 'şahin', 'şebnem'], dtype=object)

In [46]:
from sklearn.metrics.pairwise import cosine_similarity

In [48]:
similarity = cosine_similarity(vectors)

In [50]:
similarity[1]

array([0.       , 1.       , 0.       , ..., 0.       , 0.       ,
       0.0255655])

In [54]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(1694, np.float64(0.37113480951260275)),
 (585, np.float64(0.3256694736394648)),
 (5060, np.float64(0.32232918561015206)),
 (1971, np.float64(0.2984810028978546)),
 (589, np.float64(0.29346959282671103))]

In [59]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [64]:
recommend('The Starling')

Jaws 2
Jaws: The Revenge
Midnight Run
Indiana Jones and the Temple of Doom
Mutiny on the Bounty